
server:
  port: 5053

spring:
  application:
    name: Client Management
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/bytedb?currentSchema=test_cm
    username: byte_adm
    password: b1t3_4dm
    hikari:
      schema: test_cm
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 50000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Actualizado para Hibernate 6
    show-sql: false
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true

    hibernate:
      ddl-auto: none
      naming:

        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  liquibase:
    contexts: dev
    change-log: classpath:config/liquibase/master.xml